IF EXISTS(SELECT * FROM sys.databases WHERE name = 'ESEVA')
BEGIN
	USE ESEVA
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='SERVICEREQUEST' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE SERVICEREQUEST
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='SESSION' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE "SESSION"
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='USER' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE "USER"
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='DOCUMENT' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE DOCUMENT
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='SERVICE' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE SERVICE
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='LANGUAGE' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE ESEVA.DBO.LANGUAGE
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='ROLE' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE ESEVA.DBO.ROLE
END
GO

IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='STATUS' and TABLE_CATALOG='ESEVA')
BEGIN
	DROP TABLE ESEVA.DBO.STATUS
END
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name = 'ESEVA')
BEGIN
	Use master
	alter database ESEVA set single_user with rollback immediate
	DROP DATABASE ESEVA
END
GO